# fly.toml app configuration file generated for moreofa on 2024-11-18T10:43:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moreofa'
primary_region = 'ewr'

[build]
[env]
PORT = ":8080"
GOMEMLIMIT = "512MiB"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[http_service.checks]]
grace_period = "5s"
interval = "30s"
method = "GET"
timeout = "1s"
path = "/api/healthcheck"

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
