// Code generated by "stringer -type=CommentKind"; DO NOT EDIT.

package akismet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownKind-0]
	_ = x[HamKind-1]
	_ = x[SpamKind-2]
	_ = x[TrashKind-3]
}

const _CommentKind_name = "UnknownKindHamKindSpamKindTrashKind"

var _CommentKind_index = [...]uint8{0, 11, 18, 26, 35}

func (i CommentKind) String() string {
	if i < 0 || i >= CommentKind(len(_CommentKind_index)-1) {
		return "CommentKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommentKind_name[_CommentKind_index[i]:_CommentKind_index[i+1]]
}
